wandb_version: 1

dataset:
  desc: null
  value: VinDr-RibCXR
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715760409.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.16.6
      8:
      - 5
      - 13
      13: darwin-x86_64
